#!/bin/bash

echo "🐳 INSTALLATION DE DOCKER - VERSION MANUELLE"
echo "============================================"
echo ""
echo "L'installation automatique nécessite votre mot de passe administrateur."
echo ""
echo "📥 OPTION 1: Installation avec mot de passe (Recommandé)"
echo "   Exécutez cette commande dans votre terminal:"
echo ""
echo "   brew install --cask docker"
echo ""
echo "   (Vous devrez entrer votre mot de passe macOS)"
echo ""
echo "📥 OPTION 2: Téléchargement manuel"
echo "   1. Allez sur: https://www.docker.com/products/docker-desktop"
echo "   2. Téléchargez Docker Desktop pour Mac"
echo "   3. Ouvrez le fichier .dmg"
echo "   4. Glissez Docker dans Applications"
echo ""
echo "🚀 Après l'installation:"
echo "   1. Ouvrez Docker Desktop depuis Applications"
echo "   2. Attendez que Docker démarre"
echo "   3. Vérifiez: docker --version"
echo ""
