// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Allow runtime overrides (useful when .env points to a different project)
function captureUrlOverrides() {
  try {
    const params = new URLSearchParams(window.location.search);
    const url = params.get('supabaseUrl');
    const key = params.get('supabaseKey');
    if (url) localStorage.setItem('SUPABASE_URL', url);
    if (key) localStorage.setItem('SUPABASE_ANON_KEY', key);
  } catch {
    // ignore
  }
}

if (typeof window !== 'undefined') {
  captureUrlOverrides();
}

const urlOverride =
  (typeof window !== 'undefined' && (window as any).__SUPABASE_URL__) ||
  (typeof window !== 'undefined' && localStorage.getItem('SUPABASE_URL')) ||
  undefined;

const keyOverride =
  (typeof window !== 'undefined' && (window as any).__SUPABASE_KEY__) ||
  (typeof window !== 'undefined' && localStorage.getItem('SUPABASE_ANON_KEY')) ||
  undefined;

function normalizeProjectUrl(raw?: string): string | undefined {
  if (!raw) return raw;
  try {
    // If someone put a function URL (…/functions/v1/<name>), strip the path
    const u = new URL(raw);
    if (u.pathname.startsWith('/functions/')) {
      return `${u.origin}`;
    }
    return u.origin + (u.pathname === '/' ? '' : u.pathname);
  } catch {
    return raw;
  }
}

const SUPABASE_URL = normalizeProjectUrl((urlOverride as string) || import.meta.env.VITE_SUPABASE_URL)!;
const SUPABASE_PUBLISHABLE_KEY = (keyOverride as string) || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_FUNCTIONS_URL = (import.meta.env.VITE_SUPABASE_FUNCTIONS_URL as string | undefined);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  ...(SUPABASE_FUNCTIONS_URL ? { functions: { url: SUPABASE_FUNCTIONS_URL } } : {}),
});
